export const FILE_EXTENSION = 'hl';

export const keyword = {
  function: 'define',
  immutableBinding: 'let',
  // mutableBinding: 'local',
  import: 'import',
  lambda: '\\',
  type: 'type',
  typeAlias: 'type alias',
};

export const symbol = {
  anonymousConstructorInvokeBegin: '(',
  anonymousConstructorInvokeEnd: ')',
  anonymousConstructorSeparator: ',',
  anonymousConstructorTag: '@',
  bindingOperator: '=',
  commentBegin: '#',
  constructorDeclarationBegin: '|',
  constructorInvokeBegin: '(',
  constructorInvokeEnd: ')',
  constructorParameterSeparator: ',',
  docCommentBegin: '##',
  functionBegin: '=',
  functionInvokeBegin: '(',
  functionInvokeEnd: ')',
  functionParameterSeparator: ',',
  functionReturn: '->',
  genericsListBegin: '(',
  genericsListEnd: ')',
  genericsListSeparator: ',',
  labelledParameterAnnotation: ':',
  lambdaBegin: '->',
  listBegin: '[',
  listEnd: ']',
  listSeparator: ',',
  pathSeparator: '.',
  recordBegin: '@(',
  recordEnd: ')',
  recordPathSeparator: '.',
  recordSeparator: ',',
  stringBegin: '"',
  stringEnd: '"',
  stringInterpolationBegin: '\\(',
  stringInterpolationEnd: ')',
  tupleBegin: '(',
  tupleEnd: ')',
  tupleSeparator: ',',
  typeAnnotation: ':',
  typeBegin: '=',
};
