export const FILE_EXTENSION = 'he';

export const keyword = {
  bindingImmutable: 'let',
  bindingMutable: 'var',
  caseBegin: 'case',
  caseBranchBegin: '->',
  caseOf: 'of',
  function: 'define',
  ifBegin: 'if',
  ifElse: 'else',
  ifThen: 'then',
  import: 'import',
  importExposing: 'showing',
  importRename: 'as',
  lambda: '\\',
  type: 'data',
  typeAlias: 'type',
};

export const symbol = {
  anonymousConstructorInvokeBegin: '(',
  anonymousConstructorInvokeEnd: ')',
  anonymousConstructorSeparator: ',',
  anonymousConstructorTag: '@',
  bindingOperator: '=',
  commentBegin: '#',
  constructorDeclarationBegin: '|',
  constructorInvokeBegin: '(',
  constructorInvokeEnd: ')',
  constructorParameterSeparator: ',',
  docCommentBegin: '##',
  functionBegin: '=',
  functionInvokeBegin: '(',
  functionInvokeEnd: ')',
  functionParameterSeparator: ',',
  functionReturn: '->',
  genericsListBegin: '(',
  genericsListEnd: ')',
  genericsListSeparator: ',',
  importExternal: 'lib:',
  importExposedIdentifiersSeparator: ',',
  labelledParameterAnnotation: ':',
  lambdaBegin: '->',
  listBegin: '[',
  listEnd: ']',
  listSeparator: ',',
  pathSeparator: '.',
  placeholder: '???',
  recordBegin: '@(',
  recordEnd: ')',
  recordPathSeparator: '.',
  recordSeparator: ',',
  stringBegin: '"',
  stringEnd: '"',
  stringInterpolationBegin: '\\(',
  stringInterpolationEnd: ')',
  tupleBegin: '(',
  tupleEnd: ')',
  tupleSeparator: ',',
  typeAnnotation: ':',
  typeBegin: '=',
};
